# Generated by Django 5.2.14 on 2026-05-18 15:52

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=256, unique=True)),
                ('artist_slug', models.SlugField(max_length=256)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['-artist_name'],
                'indexes': [models.Index(fields=['-artist_name'], name='beatemplate_artist__3ad3ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(max_length=256)),
                ('playlist_slug', models.SlugField(max_length=256)),
                ('playlist_description', models.CharField(max_length=256)),
                ('playlist_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-playlist_date'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_title', models.CharField(max_length=256)),
                ('release_slug', models.SlugField(max_length=256)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('release_type', models.CharField(choices=[('ALBUM', 'Álbum'), ('SINGLE', 'Single')], default='ALBUM', max_length=10)),
                ('artists', models.ManyToManyField(to='beatemplate.artist')),
            ],
            options={
                'verbose_name': 'Lanzamiento',
                'verbose_name_plural': 'Lanzamientos',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=256)),
                ('song_slug', models.SlugField(max_length=256)),
                ('song_duration', models.DurationField()),
                ('artists', models.ManyToManyField(to='beatemplate.artist')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
            },
        ),
        migrations.CreateModel(
            name='ReleaseSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveIntegerField()),
                ('disc_title', models.CharField(default=None, max_length=256, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_songs', to='beatemplate.release')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_releases', to='beatemplate.song')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['disc_title', 'track_number'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_at', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='beatemplate.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_playlists', to='beatemplate.song')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['position_at'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='beatemplate.song'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['-release_date'], name='beatemplate_release_f5ec57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='releasesong',
            unique_together={('release', 'disc_title', 'track_number')},
        ),
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together={('playlist', 'position_at')},
        ),
    ]
