# Generated by Django 5.2.14 on 2026-05-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beatemplate", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlaylistSong",
        ),
    ]
