# Generated by Django 5.2.14 on 2026-05-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatemplate', '0002_delete_playlistsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
