# Generated by Django 5.2.14 on 2026-05-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatemplate', '0003_alter_playlist_playlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasesong',
            name='disc_title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
