# Generated by Django 5.2.14 on 2026-05-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatemplate', '0004_alter_releasesong_disc_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasesong',
            name='disc_title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
