# Configuración

server {
    listen 8000;
    
    location /static/ {
        alias /staticfiles_beatemplate/; 
    }
    
    location / {
        proxy_pass http://web-beatemplate:8000;
        proxy_set_header Host $host;
    }
}

# Configuración para la API

server {
    listen 8001;
    
    location /static/ {
        alias /staticfiles_restemplate/; 
    }
    
    location / {
        proxy_pass http://web-api:8001;
        proxy_set_header Host $host;
    }
}