# Generated by Django 5.2.14 on 2026-05-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restemplate", "0002_alter_rating_score_alter_rating_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.IntegerField(),
        ),
    ]
